--- 
models: 
  user: 
    associations: 
    - notes: has_many
    - lp_requests: has_many
    - role: belongs_to
    - options: 
        through: notes
      lp_requests: has_many
    - options: 
        through: notes
      customers: has_many
    - options: 
        through: notes
      link_partners: has_many
    - options: 
        through: notes
      link_partners: has_many
    - options: 
        through: lp_requests
      link_partners: has_many
    attributes: 
    - password: string
    - email: email
    - firstname: string
    - lastname: string
    - time_worked: string
  link_partner_order_member: 
    associations: 
    - order: belongs_to
    - link_partner: belongs_to
    attributes: 
    - status: integer
  category: 
    associations: 
    - link_partners: has_many
    - mail_templates: has_many
    - link_partners: has_many
    - options: 
        through: link_partners
      link_partners: has_many
    - webmasters: has_many
      options: 
        through: link_partners
    - options: 
        through: link_partners
      link_partners: has_many
    - webmasters: has_many
      options: 
        through: link_partners
    attributes: 
    - name: string
  order: 
    associations: 
    - customer: belongs_to
    - link_partner_order_members: has_many
    - options: 
        through: link_partner_order_members
      link_partners: has_many
    attributes: 
    - hours_needed: integer
    - links_needed: integer
    - alias: string
    - status: integer
    - email_from: integer
    - email_method: integer
    - success_percentage: integer
    - landings_page: url
    - search_keyword: string
    - link_keyword: string
  link_partner: 
    associations: 
    - link_partner_order_members: has_many
    - subdomains: has_many
    - category: belongs_to
    - mail_template: belongs_to
    - lp_requests: has_many
    - notes: has_many
    - category: belongs_to
    - webmaster: belongs_to
    - notes: has_many
    - options: 
        through: link_partner_order_members
      orders: has_many
    - webmasters: has_many
      options: 
        through: subdomains
    - options: 
        through: lp_requests
      users: has_many
    - options: 
        through: notes
      lp_requests: has_many
    - options: 
        through: notes
      customers: has_many
    - options: 
        through: notes
      users: has_many
    - options: 
        through: notes
      lp_requests: has_many
    - options: 
        through: notes
      customers: has_many
    - options: 
        through: notes
      users: has_many
    attributes: 
    - domain: domain
    - title: string
    - description: text
    - page_rank: integer
  webmaster: 
    associations: 
    - subdomains: has_many
    - link_partners: has_many
    - options: 
        through: subdomains
      link_partners: has_many
    - options: 
        through: link_partners
      categories: has_many
    - options: 
        through: link_partners
      categories: has_many
    attributes: 
    - email: email
  subdomain: 
    associations: 
    - link_partner: belongs_to
    - webmaster: belongs_to
    attributes: 
    - url: url
  role: 
    associations: 
    - users: has_many
    attributes: 
    - name: string
  mail_template: 
    associations: 
    - link_partner: belongs_to
    - category: belongs_to
    attributes: 
    - body: text
    - subject: string
    - title: string
    - email_method: integer
  note: 
    associations: 
    - lp_request: belongs_to
    - customer: belongs_to
    - link_partner: belongs_to
    - user: belongs_to
    - link_partner: belongs_to
    attributes: 
    - body: text
  customer: 
    associations: 
    - orders: has_many
    - notes: has_many
    - options: 
        through: notes
      lp_requests: has_many
    - options: 
        through: notes
      link_partners: has_many
    - options: 
        through: notes
      users: has_many
    - options: 
        through: notes
      link_partners: has_many
    attributes: 
    - name: domain
    - email: email
  lp_request: 
    associations: 
    - link_partner: belongs_to
    - notes: has_many
    - user: belongs_to
    - options: 
        through: notes
      customers: has_many
    - options: 
        through: notes
      link_partners: has_many
    - options: 
        through: notes
      users: has_many
    - options: 
        through: notes
      link_partners: has_many
    attributes: 
    - status: integer
    - email_body: text
    - response: text
