--- 
models: 
  blacklist: 
    attributes: 
    - domain: url
  link_partner_order_member: 
    associations: 
    - belongs_to: link_partner
    - belongs_to: order
    options: 
      paginate: true
      per_page: 10
    attributes: 
    - selected: boolean
  search: 
    associations: 
    - polymorphic: true
      belongs_to: searchable
    attributes: 
    - searchable_type: string
    - query: string
    - language: string
    - region: string
    - strict_language: boolean
    - limit: integer
    - done: boolean
    - deep_hits: integer
    - total_hits: integer
    concerned_with: attributes
  competitor: 
    associations: 
    - has_many: order_competitor_members
    - has_many: orders
      through: order_competitor_members
    attributes: 
    - domain: domain
    - title: string
    - description: text
  link_partner: 
    associations: 
    - has_and_belongs_to_many: competitors
    - has_and_belongs_to_many: products
    - has_many: link_partner_order_members
    - has_many: orders
      through: link_partner_order_members
    attributes: 
    - domain: url
    - title: string
    - description: text
    - page_rank: integer
    concerned_with: attributes
  order: 
    associations: 
    - belongs_to: product
    - class_name: Search
      as: searchable
      has_many: competitor_searches
    - has_many: order_competitor_members
    - has_many: competitors
      through: :order_competitor_members
    - class_name: Search
      as: searchable
      has_many: link_partner_searches
    - has_many: link_partner_order_members
    - has_many: link_partners
      through: link_partner_order_members
    attributes: 
    - query: string
    - language: string
    - region: string
    - strict_language: boolean
    - scraping_started: boolean
    - scraping_done: boolean
    - link_partners_per_competitor: integer
    - offset_link_partners: integer
    concerned_with: attributes
  product: 
    associations: 
    - belongs_to: customer
    - has_many: orders
    attributes: 
    - name: string
  customer: 
    associations: 
    - has_many: products
    attributes: 
    - name: string
  order_competitor_member: 
    associations: 
    - belongs_to: order
    - belongs_to: competitor
